

CREATE TABLE IF NOT EXISTS `vol` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date_dep` DATETIME NOT NULL ,
  `date_arr` DATETIME NOT NULL ,
  `classe` VARCHAR(20) NOT NULL ,
  `nb_adultes` SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  `nb_enfants` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `dateAjout` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_dateAjout` (`dateAjout`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

